
version: '3.1'

services:

  db-facial:
    image: postgres:15.2-alpine
    container_name: ${DB_USERNAME}
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      TZ: 'America/El_Salvador'
      PGTZ: 'America/El_Salvador'