
version: '3.1'

services: 

  nestjsapp:
    depends_on:
      - db-facial
    build: 
      context: .
      dockerfile: Dockerfile
    image: nestjs-docker
    container_name: nestjsapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"  
    env_file: .env
    networks:
      - mynetwork 
    environment:
      VARIABLE1: valor1
      VARIABLE2: valor2
    # entrypoint: ["npx", "prisma", "migrate", "deploy"]
    

  db-facial:
    image: postgres:15.2-alpine
    container_name: ${DB_HOST}
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      TZ: 'America/El_Salvador'
      PGTZ: 'America/El_Salvador'
    networks:
      - mynetwork

networks:
  mynetwork: